# -*- coding: utf-8 -*-
"""sports vs politics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14ECa4thXzurVhU4qGqHFXRWRl0i0rNkC
"""

#checking all the present labels
import pandas as pd

data = pd.read_csv("bbc_data.csv")

print(data.head())
print(data["labels"].value_counts())

# Filter only sport and politics
filtered = data[data["labels"].isin(["sport", "politics"])].copy()

# Convert labels into binary numbers
# sports has the binary 0 and politics has binary 1
filtered["label"] = filtered["labels"].map({
    "sport": 0,
    "politics": 1
})

# Check result
print(filtered["labels"].value_counts())
print(filtered.head())

#splitting of data for test and train
from sklearn.model_selection import train_test_split

X = filtered["data"]     # text column
y = filtered["label"]    # numeric label

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Training label distribution:")
print(y_train.value_counts())

print("\nTesting label distribution:")
print(y_test.value_counts())

#feature extraction by TF-IDF+ngrams
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(stop_words="english", ngram_range=(1,2))

X_train_vec = tfidf.fit_transform(X_train)
X_test_vec = tfidf.transform(X_test)

# training three models
#naive bayes
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

nb = MultinomialNB()
nb.fit(X_train_vec, y_train)

pred_nb = nb.predict(X_test_vec)
print("Naive Bayes Accuracy:", accuracy_score(y_test, pred_nb))

#logistic regression
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(max_iter=200)
lr.fit(X_train_vec, y_train)

pred_lr = lr.predict(X_test_vec)
print("Logistic Regression Accuracy:", accuracy_score(y_test, pred_lr))

#support vector machine
from sklearn.svm import LinearSVC

svm = LinearSVC()
svm.fit(X_train_vec, y_train)

pred_svm = svm.predict(X_test_vec)
print("SVM Accuracy:", accuracy_score(y_test, pred_svm))

#comparison table
import pandas as pd
from sklearn.metrics import accuracy_score

results = pd.DataFrame({
    "Model": ["Naive Bayes", "Logistic Regression", "SVM"],
    "Accuracy": [
        accuracy_score(y_test, pred_nb),
        accuracy_score(y_test, pred_lr),
        accuracy_score(y_test, pred_svm)
    ]
})

results